### PR TITLE
Airtable schema migration cont.

### PR DESCRIPTION
**Pull request by dangalan**
Continuation of [this merged then reverted PR](https://github.com/MutualAidNYC/services-lists/pull/50).

### CODE REVIEW

**Comment by vronnieli** [comment]
I had trouble getting this working on my machine, but then realized you added a column to the MANYC Groups Airtable, could you replicate whatever changes you made there to the MANYC Groups (Dev) Airtable (you should have access). That said, there's something funky going on with the Needs pills on published lists (I published one to test). Also clicking through to a published list page isn't properly displaying the resources in that list, I'm not sure if the resources are being properly filtered. Last note, do we want to move away from using the word 'services' in the codebase/api (this isn't urgent though).

Screen Shot 2023-01-06 at 12 10 15 AM

**Comment by dangalan** [comment]
> I had trouble getting this working on my machine, but then realized you added a column to the MANYC Groups Airtable, could you replicate whatever changes you made there to the MANYC Groups (Dev) Airtable (you should have access). That said, there's something funky going on with the Needs pills on published lists (I published one to test). Also clicking through to a published list page isn't properly displaying the resources in that list, I'm not sure if the resources are being properly filtered. Last note, do we want to move away from using the word 'services' in the codebase/api (this isn't urgent though).
> 
> Screen Shot 2023-01-06 at 12 10 15 AM

- Which column? I don't think I added any since you made a copy of the Airtable base for dev but I can check.
- Good catch on the needs pills - not sure what's going on there but I can take a look. 
- Good catch with the list page too, will take a look. Tbh I was more focused on the `Create` page since with Gracie's redesign resources themselves will become the like starting point of the site instead of lists.
- I made a comment about "services" vs "resources" in the PR the got merged than reverted and added it to a list of tech debt on the Notion page (should we just convert all these tech debt bullets to more tickets?) - imo, we should do that refactor in a separate PR b/c this PR is already big as is. 

Do we think it's worth fixing all this wonky functionality in this PR though? Imo, it might be better to just turn off auto-deploys on merges to master (at least in prod) so we can merge this and work off of it, especially since a lot this functionality is gonna get reworked.

**Comment by dangalan** [comment]
Looking more into the needs pills, this is because the `Needs` column on the `Resources` table that the resource list's `taxonomies' field is a bunch of comma separated strings that combine the the `Needs Entry` and `Other Needs Entry` field. Not sure who set it up that up or how we wanna use `Needs Entry` and `Other Needs Entry`.

**Review by notnazsty — COMMENTED** [review]
It works on my local machine, and I haven't found any of the previous Airtable errors.

**Review by notnazsty — APPROVED** [review]

**Pull request merged**
