### PR TITLE
Adding mapbox component (test) 

### PR DESCRIPTION
**Pull request by btmoore4**
Here is an example of the map component. 
Might need to add access token directly to Map Component.

### CODE REVIEW

**Review by notnazsty — APPROVED** [review]

**Review by dangalan — APPROVED** [review]

**Comment by dangalan** [comment]
@btmoore4 did you get features rendering when you ran this locally? Trying to work off your branch and the map is rendering but without any features on it for me.

**Comment by btmoore4** [comment]
it looks like the env variable is not working, but if you replace the KEY in the Mapbox API javascript file it looks good

**Comment by dangalan** [comment]
Hmm, I think we need to prefix our env variable with [NEXT_PUBLIC_](https://nextjs.org/docs/basic-features/environment-variables#exposing-environment-variables-to-the-browser) for us to use it anywhere in our code but I tried that and it still wasn't working for me. 

When you say replace the key, which Mapbox file are you referring to? Like directly modifying something downloaded to `node_modules`?

**Comment by btmoore4** [comment]
If you replace the var on line 5 of Map.tsx with your mapbox token. That def works for me 
`accessToken: process.env.MAP_BOX_ACCESS_TOKEN`

**Comment by dangalan** [comment]
Just tried that too but it's not working for me either. I guess we can check in about it on Monday.

**Pull request merged**
